abdellah/urls.py
from django.urls import path
from . import views

urlpatterns = [ 
    path('', views.index, name = 'index'),
]

portfolio_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('abdellah.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

abdellah/models.py
from django.db import models
from PIL import Image
# Create your models here.
class Home(models.Model):
    name = models.CharField(max_length=25)
    logo1 = models.CharField(max_length=20)
    logo2 = models.CharField(max_length=20)

    greetings_1 = models.CharField(max_length= 20)
    greetings_2 = models.CharField(max_length= 255)
    greetings_3 = models.CharField(max_length= 255)
    greetings_4 = models.CharField(max_length= 255)
    greetings_5 = models.CharField(max_length= 255)

    
    picture = models.ImageField(upload_to='picture/')
    picturephone = models.ImageField(upload_to='picture/')

    updated = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.picture:
            self.compress_and_optimize_image(self.picture)

        if self.picturephone:
            self.compress_and_optimize_image(self.picturephone)

    def compress_and_optimize_image(self, image_field):
        img = Image.open(image_field.path)
        img.save(image_field.path, quality=20, optimize=True)

    def __str__(self):
        return self.logo1
    

class About(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank = False)
    profile_img = models.ImageField(upload_to='profile/')

    updated = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.compress_and_optimize_image()

    def compress_and_optimize_image(self):
        img = Image.open(self.profile_img.path)
        img.save(self.profile_img.path, quality=20, optimize=True)

    def __str__(self):
        return self.name
    
class Profile(models.Model):
    about = models.ForeignKey(About,
                              on_delete = models.CASCADE)
class Category(models.Model):
    name = models.CharField(max_length=20)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'

    def __str__(self):
        return self.name
    
class Skills(models.Model):
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE)
    skill_name = models.CharField(max_length=20)
    skill_description = models.TextField(blank=False)

class ExperienceCategory(models.Model):
    name = models.CharField(max_length=20)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Experience Category'
        verbose_name_plural = 'Experience Categories'

    def __str__(self):
        return self.name

class Experience(models.Model):
    experiencecategory = models.ForeignKey(ExperienceCategory, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    description = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.title
class EducationCategory(models.Model):
    name = models.CharField(max_length=20)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Education Category'
        verbose_name_plural = 'Education Categories'

    def __str__(self):
        return self.name
class Education(models.Model):
    educationcategory = models.ForeignKey(EducationCategory, on_delete=models.CASCADE)
    degree = models.CharField(max_length=50)
    field_of_study = models.CharField(max_length=50)
    university = models.CharField(max_length=100)
    graduation_date = models.DateField()

    def __str__(self):
        return self.degree
    
class Service(models.Model):
    logo = models.TextField()
    name = models.CharField(max_length=50)
    description = models.TextField()
    link = models.URLField()

    def __str__(self):
        return self.name
    

class WorkCategory(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Work(models.Model):
    category = models.ForeignKey(WorkCategory, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='works/')
    link = models.URLField()

    def __str__(self):
        return self.title
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.compress_and_optimize_image()

    def compress_and_optimize_image(self):
        img = Image.open(self.image.path)
        img.save(self.image.path, quality=50, optimize=True)

class Socials(models.Model):
    name = models.CharField(max_length=50)
    phone = models.IntegerField(default=0)
    email = models.EmailField()
    Facebook = models.URLField()
    Instagram = models.URLField()
    LinkedIn = models.URLField()

    def __str__(self):
        return self.name

abdellah/views.py
from django.shortcuts import render
from .models import Home, About, Category, Profile,ExperienceCategory, EducationCategory, Service, WorkCategory, Work, Socials

def index(request):
    home = Home.objects.latest('updated')
    about = About.objects.latest('updated')
    profiles = Profile.objects.filter(about=about)
    categories = Category.objects.all()
    experiences = ExperienceCategory.objects.all()
    education = EducationCategory.objects.all()
    services = Service.objects.all()
    work_categories = WorkCategory.objects.all()
    works = Work.objects.all()
    socials=Socials.objects.all()
    context = {
        'home' : home,
        'about' : about,
        'profiles' : profiles,
        'categories' : categories,
        'experiences':experiences,
        'education' : education,
        'services' : services,
        'work_categories': work_categories,
        'works': works,
        'socials' : socials,
                }


    return render(request, 'index.html', context)

abdellah/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{home.name}}</title>
    
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <script src="https://kit.fontawesome.com/481f6f7e30.js" crossorigin="anonymous"></script>
    <style>
        #header {
            width: 100%;
            height: 100vh;
            background-image: url('{{ home.picture.url }}'); /* Use your Django template tag here */
            background-size: cover;
            background-position: center;
            padding: 50px 20px;
        }
        @MEDIA only screen and (max-width: 600px){
    #header{
        background-image: url('{{ home.picturephone.url }}');
        padding: 20px 1px;
    }}
    </style>
    
</head>
<body>
   <div id="header">
    <div class="container">
        <nav>
            <a href="#" class="logo" style="font-size: 36px;
            color: white;
            font-weight: 600; text-decoration: none;">{{ home.logo1 }}<span style="color: #13bbff;"> {{home.logo2}}</span></a>
            <ul class="navlist" id="sidemenu">
                <li><a href="#header">Home</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#services">Services</a></li>
                <li><a href="#portfolio">Portfolio</a></li>
                <li><a href="#contact">Contact</a></li>
                <li><a href="{% url 'admin:index' %}">Admin</a></li>

                <i class="fa-solid fa-circle-xmark" onclick="closemenu()"></i>
            </ul>
            <i class="fa-solid fa-bars" onclick="openmenu()"></i>
        </nav>
        <div class="header-text">
            <p>{{ home.greetings_1 }}</p>
            <h1>I'm <span class="input"></span></h1>
        </div>
    </div>
</div> 

<!----about----->
<div id="about">
    <div class="container">
        <div class="row">
            <div class="about-col-1"><img src="{{ about.profile_img.url }}" ></div>
            <div class="about-col-2">
                <h1 class="sub-title">About Me</h1>
                <p>{{ about.description }}</p>
                <div class="tab-titles">
                    <p class="tab-links active-link" onclick="opentab('skills')">Skills</p>
                    <p class="tab-links" onclick="opentab('experience')">Experience</p>
                    <p class="tab-links" onclick="opentab('education')">Education</p>
                </div>
                <div class="tab-contents active-tab" id="skills">
                    <ul>
                        {% for category in categories %}
                        {% for skills in category.skills_set.all %}
                        <li><span>{{skills.skill_name}}</span><br>{{skills.skill_description}}</li>
                        {% endfor %}
                        {% endfor %}
                       

                    </ul>
                </div>
                <div class="tab-contents" id="experience">
                    <ul>
                        {% for experiencecategory in experiences %}
                        {% for experience in experiencecategory.experience_set.all %}
                            <li>
                                <span>{{ experience.start_date|date:"Y" }}{% if experience.end_date %}-{{ experience.end_date|date:"Y" }}{% else %}-Current{% endif %}</span>
                                <br>{{ experience.title }}
                                <br>{{ experience.description }}
                            </li>
                        {% endfor %}
                    {% endfor %}

                    </ul>
                </div>
                <div class="tab-contents" id="education">
                    <ul>
                        {% for educationcategory in education %}
                        {% for education in educationcategory.education_set.all %}
                        <li><span>{{education.degree}}</span><br>{{education.field_of_study}} <br>{{education.university}} {{education.graduation_date}}</li>
                        {% endfor %}
                    {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<!---services-->
<div id="services">
    <div class="container">
        <h1 class="sub-title">My services</h1>
        <div class="services-list">
            {% for service in services %}
            <div>
                
                    <i class="{{service.logo}}"></i>
                    <h2>{{ service.name }}</h2>
                    <p>{{ service.description }}</p>
                    <a href="#">Learn more</a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- Portfolio -->
<div id="portfolio">
    <div class="container">
        <h1 class="sub-title">My work</h1>
        <div class="work-titles">
            {% for category in work_categories %}
            <p class="work-links {% if forloop.first %}active-work{% endif %}" data-work="{{ category.name }}" onclick="openWork('{{ category.name }}')">{{ category.name }}</p>
            {% endfor %}
        </div>
        <div class="work-list">
            {% for category in work_categories %}
            <div class="work-contents {% if forloop.first %}active-work1{% endif %}" id="{{ category.name }}-content">
                {% for work in works %}
                {% if work.category == category %}
                <div class="work-item">
                    <img src="{{ work.image.url }}" height="400px" width="310px">
                    <div class="layer">
                        <h3>{{ work.title }}</h3>
                        <p>{{ work.description }}</p>
                        <a href="{{work.link}}"><i class="fa-solid fa-link"></i></a>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
            {% endfor %}
        </div>
    </div>
    <a href="https://www.instagram.com/abdellah_zou/" target="_blank" class="btn">See more</a>
</div>

</div>
<!--contact-->
<div id="contact">
    <div class="container">
        <div class="row">
            <div class="contact-left">
                <h1 class="sub-title">Contact me</h1>
                {% for social in socials %}
                    <p><i class="fa-solid fa-paper-plane"></i> {{ social.email }}</p>
                    <p><i class="fa-solid fa-phone"></i>{{ social.phone }}</p>
                    <div class="social-icons">
                        <a href="{{ social.Facebook }}" target="_blank"><i class="fa-brands fa-square-facebook"></i></a>
                        <a href="{{ social.LinkedIn }}" target="_blank"><i class="fa-brands fa-linkedin"></i></a>
                        <a href="{{ social.Instagram }}" target="_blank"><i class="fa-brands fa-square-instagram"></i></a>

                    </div>
                {% endfor %}
                <a href="#" download class="btn btn2">Download CV</a>
            </div>
            <div class="contact-right">
                <form name="submit-to-google-sheet">
                    <input type="text" name="Name" placeholder="Your Name" required>
                    <input type="text" name="Email" placeholder="Your Email" required>
                    <textarea name="Message"  rows="6" placeholder="Your Message"></textarea>
                    <button type="submit" class="btn btn2">Submit</button>
                </form>
                <span id="msg"></span>
            </div>
        </div>
    </div>
</div>

    <div class="copyright">
        <p> Design  Copyright &copy; Kevin, Made with <i class="fa-solid fa-heart"></i> by Abdellah Zouggari  </p>
    </div>
</div>















<!--Script for about section-->
<script>
    var tablinks = document.getElementsByClassName("tab-links");
    var tabcontents = document.getElementsByClassName("tab-contents");
    function opentab(tabname){
        for(tablink of tablinks){
            tablink.classList.remove("active-link");
        }
        for(tabcontent of tabcontents){
            tabcontent.classList.remove("active-tab");
    }
    event.currentTarget.classList.add("active-link");
    document.getElementById(tabname).classList.add("active-tab")
    
    }
</script>
<!--Script for my work section-->
<script>
function openWork(workType) {
    var workContents = document.getElementsByClassName("work-contents");
    var workTitles = document.getElementsByClassName("work-links");

    for (var i = 0; i < workContents.length; i++) {
        workContents[i].classList.remove("active-work1");
    }

    for (var i = 0; i < workTitles.length; i++) {
        workTitles[i].classList.remove("active-work");
    }

    var activeWorkContent = document.getElementById(workType + "-content");
    var activeWorkTitle = document.querySelector("[data-work='" + workType + "']");

    activeWorkContent.classList.add("active-work1");
    activeWorkTitle.classList.add("active-work");
}

</script>


<script src="https://unpkg.com/typed.js@2.0.16/dist/typed.umd.js"></script>
<script>
 var typed= new Typed(
     ".input", {
         strings:["{{ home.greetings_2}}", "{{ home.greetings_3 }}", "{{ home.greetings_4 }}", "{{ home.greetings_5 }}"],
         typeSpeed:70,
         backSpeed:65,
         loop:true
     }
 )
</script>
<!--side menu--->
<script>
    var sidemenu = document.getElementById("sidemenu");
    function openmenu(){
        sidemenu.style.right = "0";
    }
    function closemenu(){
        sidemenu.style.right="-200px";
    }
</script>
<!---contact form message-->
<script>
    const scriptURL = 'https://script.google.com/macros/s/AKfycbz8Z76xE7-9Mf2j7GkUTvxHDeeHn_L49umeMXxtvsnWOal4y1Z9K-pu0Wlv_h1Z4_I4/exec'
    const form = document.forms['submit-to-google-sheet']
    const msg = document.getElementById("msg")

    form.addEventListener('submit', e => {
      e.preventDefault()
      fetch(scriptURL, { method: 'POST', body: new FormData(form)})
        .then(response => {
            msg.innerHTML = "Message sent successfully"
            setTimeout(function(){
                msg.innerHTML = ""
            },5000)
            form.reset()
        })
        .catch(error => console.error('Error!', error.message))
    })
  </script>
  <!--scroll reveal-->
  <script src="https://unpkg.com/scrollreveal"></script>
   <script src="{% static 'assets/js/main.js' %}"></script> 


</body>
</html>

abdellah/templates/original/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
    <!---remixicons for icons --->
    <link href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css" rel="stylesheet">
<!--- google fonts--->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">


</head>
<body>
    <header>
        <a href="#" class="logo">Abdellah <span>Zou.</span></a>
        <ul class="navlist">
            <li> <a href="#" class="active">Home</a></li>
            <li> <a href="#">About</a></li>
            <li> <a href="#">Service</a></li>
            <li> <a href="#">Portfolio</a></li>
            <li> <a href="#">Contact</a></li>

        </ul>
        <div class="top-btnn">
            <a href="#" class="h-btn">Contact me</a>
        </div>
    </header>

    <section class="hero">
        <div class="main-content">
            <h4>{{ home.greetings_1 }}</h4>
            <h1>I'm <span class="input"> </span></h1>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Deleniti et architecto accusantium repellendus id quibusdam quas beatae quis sunt nam nulla ex, enim, ad nesciunt, sapiente libero laborum iste consequatur?</p>
            <div class="social">
                <a href="#"><i class="ri-instagram-line"></i></a>
                <a href="#"><i class="ri-facebook-box-line"></i></a>
                <a href="#"><i class="ri-linkedin-box-line"></i></a>
                <a href="#"><i class="ri-mail-line"></i></a>
            </div>
            <div class="main-btnn">
                <a href="#" class="btn">Hire me</a>
                <a href="#" class="btn btn2">Download CV</a>
    
            </div>
        </div>
        <div class="bottom">
            <p>Copyright 2023- Designed by Tahmid Ahmed, Build by Abdellah Zouggari</p>
            </div>
     
    </section>
     <!--===== ABOUT =====-->
     <section class="about section" id="about">
        <h2 class="section-title">About</h2>

        <div class="about__container bd-grid">
            <div class="about__img">
                <img src="{{ about.picture.url }}" alt="">
            </div>

            <div>
                <h2 class="about__subtitle">{{ about.heading }}</h2>
                <span class="about__profession">{{ about.career }}</span>
                <p class="about__text">{{ about.description }}</p>

                <div class="about__social">
                    <a href="https://www.linkedin.com/in/abdellah-zouggari-59195a245/" class="about__social-icon"><i class='bx bxl-linkedin' ></i></a>
                    <a href="https://www.facebook.com/Abdellah.zouggari/" class="footer__social"><i class='bx bxl-facebook' ></i></a>
                    <a href="https://www.instagram.com/abdellah_zou/" class="footer__social"><i class='bx bxl-instagram' ></i></a>
                </div>
            </div>
        </div>
    </section>

    <!--===== SKILLS =====-->
    <section class="skills section" id="skills">
        <h2 class="section-title">Skills</h2>

        <div class="skills__container bd-grid">
            <div class="skills__box">
                <div class="skills__box">

                {% for category in categories %}
                <h3 class="skills_subtitle">{{category.name}}</h3>
                    {% for skills in category.skills_set.all %}
                        <span class="skills_name">{{skills.skill_name}}</span>
                    {% endfor %}
                {% endfor %}
                </div>
             </div>
            <div class="skills__img">
                <img src="{% static 'assets/img/skill.jpg' %}" alt="">
            </div>
        </div>
    </section>
    <!--===== PORTFOLIO =====-->
    <section class="portfolio section" id="portfolio">
        <h2 class="section-title">Portfolio</h2>

        <div class="portfolio__container bd-grid">
            {% for portfolio in portfolios %}
            <div class="portfolio__img">
                <img src="{{ portfolio.image.url }}" alt="">

                <div class="portfolio__link">
                    <a href="{{ portfolio.link }}" class="portfolio__link-name">View details</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </section> 

    <!--===== CONTACT =====-->
    <section class="contact section" id="contact">
        <h2 class="section-title">Contact</h2>

        <div class="contact__container bd-grid">
            <div class="contact__info">
                <h3 class="contact__subtitle">EMAIL</h3>
                <span class="contact__text">abdellahzouggari28@gmail.com</span>

                <h3 class="contact__subtitle">PHONE</h3>
                <span class="contact__text">+21366254106</span>

                <h3 class="contact__subtitle">ADRESS</h3>
                <span class="contact__text">Khemis El Khechna, Boumerdes, Algeria</span>
            </div>
        </div>
    </section>
</main>

<!--===== FOOTER =====-->
<footer class="footer section">
    <div class="footer__container bd-grid">
        <div class="footer__data">
            <h2 class="footer__title">Abdellah Zouggari</h2>
            <p class="footer__text">I'm Abdellah Zouggari and this is my personal website</p>
        </div>

        <div class="footer__data">
            <h2 class="footer__title">EXPLORE</h2>
            <ul>
                <li><a href="#home" class="footer__link">Home</a></li>
                <li><a href="#about" class="footer__link">About</a></li>
                <li><a href="#skills" class="footer__link">Skills</a></li>
                <li><a href="#portfolio" class="footer__link">Portfolio</a></li>
                <li><a href="#Contact" class="footer__link">Contact</a></li>
            </ul>
        </div>
        
        <div class="footer__data">
            <h2 class="footer__title">FOLLOW</h2>
            <a href="https://www.facebook.com/Abdellah.zouggari/" class="footer__social"><i class='bx bxl-facebook' ></i></a>
            <a href="https://www.instagram.com/abdellah_zou/" class="footer__social"><i class='bx bxl-instagram' ></i></a>
        </div>


    </div>
</footer>










    <script src="https://unpkg.com/scrollreveal"></script>
   <script src="{% static 'assets/js/script.js' %}"></script> 
   <script src="https://unpkg.com/typed.js@2.0.16/dist/typed.umd.js"></script>
   <script>
    var typed= new Typed(
        ".input", {
            strings:["{{ home.greetings_2 }}", "a Web Developer", "a Networking engineer", "a Photographer"],
            typeSpeed:70,
            backSpeed:65,
            loop:true
        }
    )
   </script>




</body>
</html>

abdellah/templates/original/index1.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- ===== CSS ===== -->
        <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">

        <!-- ===== BOX ICONS ===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

        <title>Abdellah Zouggari</title>
    </head>
    <body>
        <!--===== HEADER =====-->
        <header class="l-header">
            <nav class="nav bd-grid">
                <div>
                    <a href="#" class="nav__logo">{{ home.name }}</a>
                </div>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item"><a href="#home" class="nav__link active">Home</a></li>
                        <li class="nav__item"><a href="#about" class="nav__link">About</a></li>
                        <li class="nav__item"><a href="#skills" class="nav__link">Skills</a></li>
                        <li class="nav__item"><a href="#portfolio" class="nav__link">Portfolio</a></li>
                        <li class="nav__item"><a href="#contact" class="nav__link">Contact</a></li>
                    </ul>
                </div>

                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
        </header>

        <main class="l-main">
            <!--===== HOME =====-->
            <section class="home" id="home">
                <div class="home__container bd-grid">
                    <h1 class="home__title"><span>{{ home.greetings_1 }}</span><br>{{ home.greetings_2 }}</h1>

                    <div class="home__scroll">
                        <a href="#about" class="home__scroll-link"><i class='bx bx-up-arrow-alt' ></i>Scroll down</a>
                    </div>

                    <img src="{{ home.picture.url }}" alt="" class="home__img">
                </div>
            </section>
            
            <!--===== ABOUT =====-->
            <section class="about section" id="about">
                <h2 class="section-title">About</h2>

                <div class="about__container bd-grid">
                    <div class="about__img">
                        <img src="{{ about.picture.url }}" alt="">
                    </div>

                    <div>
                        <h2 class="about__subtitle">{{ about.heading }}</h2>
                        <span class="about__profession">{{ about.career }}</span>
                        <p class="about__text">{{ about.description }}</p>

                        <div class="about__social">
                            <a href="https://www.linkedin.com/in/abdellah-zouggari-59195a245/" class="about__social-icon"><i class='bx bxl-linkedin' ></i></a>
                            <a href="https://www.facebook.com/Abdellah.zouggari/" class="footer__social"><i class='bx bxl-facebook' ></i></a>
                            <a href="https://www.instagram.com/abdellah_zou/" class="footer__social"><i class='bx bxl-instagram' ></i></a>
                        </div>
                    </div>
                </div>
            </section>

            <!--===== SKILLS =====-->
            <section class="skills section" id="skills">
                <h2 class="section-title">Skills</h2>

                <div class="skills__container bd-grid">
                    <div class="skills__box">
                        <div class="skills__box">

                        {% for category in categories %}
                        <h3 class="skills_subtitle">{{category.name}}</h3>
                            {% for skills in category.skills_set.all %}
                                <span class="skills_name">{{skills.skill_name}}</span>
                            {% endfor %}
                        {% endfor %}
                        </div>
                     </div>
                    <div class="skills__img">
                        <img src="{% static 'assets/img/skill.jpg' %}" alt="">
                    </div>
                </div>
            </section>

            <!--===== PORTFOLIO =====-->
            <section class="portfolio section" id="portfolio">
                <h2 class="section-title">Portfolio</h2>

                <div class="portfolio__container bd-grid">
                    {% for portfolio in portfolios %}
                    <div class="portfolio__img">
                        <img src="{{ portfolio.image.url }}" alt="">

                        <div class="portfolio__link">
                            <a href="{{ portfolio.link }}" class="portfolio__link-name">View details</a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </section> 

            <!--===== CONTACT =====-->
            <section class="contact section" id="contact">
                <h2 class="section-title">Contact</h2>

                <div class="contact__container bd-grid">
                    <div class="contact__info">
                        <h3 class="contact__subtitle">EMAIL</h3>
                        <span class="contact__text">abdellahzouggari28@gmail.com</span>

                        <h3 class="contact__subtitle">PHONE</h3>
                        <span class="contact__text">+21366254106</span>

                        <h3 class="contact__subtitle">ADRESS</h3>
                        <span class="contact__text">Khemis El Khechna, Boumerdes, Algeria</span>
                    </div>
                </div>
            </section>
        </main>

        <!--===== FOOTER =====-->
        <footer class="footer section">
            <div class="footer__container bd-grid">
                <div class="footer__data">
                    <h2 class="footer__title">Abdellah Zouggari</h2>
                    <p class="footer__text">I'm Abdellah Zouggari and this is my personal website</p>
                </div>

                <div class="footer__data">
                    <h2 class="footer__title">EXPLORE</h2>
                    <ul>
                        <li><a href="#home" class="footer__link">Home</a></li>
                        <li><a href="#about" class="footer__link">About</a></li>
                        <li><a href="#skills" class="footer__link">Skills</a></li>
                        <li><a href="#portfolio" class="footer__link">Portfolio</a></li>
                        <li><a href="#Contact" class="footer__link">Contact</a></li>
                    </ul>
                </div>
                
                <div class="footer__data">
                    <h2 class="footer__title">FOLLOW</h2>
                    <a href="https://www.facebook.com/Abdellah.zouggari/" class="footer__social"><i class='bx bxl-facebook' ></i></a>
                    <a href="https://www.instagram.com/abdellah_zou/" class="footer__social"><i class='bx bxl-instagram' ></i></a>
                </div>


            </div>
        </footer>

        <!--===== SCROLL REVEAL =====-->
        <script src="https://unpkg.com/scrollreveal"></script>

        <!--===== MAIN JS =====-->
        <script src="{% static 'assets/js/main.js' %}"></script>
    </body>
</html>